[project]
name = "call-me-maybe"
version = "0.1.0"
description = "Function calling with constrained decoding on Qwen3-0.6B"
requires-python = ">=3.10"
dependencies = [
    "numpy>=1.26",
    "pydantic>=2.7",
    "llm-sdk",
    "accelerate>=1.0",
]

[dependency-groups]
dev = [
    "flake8>=7",
    "flake8-pyproject>=1.2",
    "mypy>=1.10",
]

[tool.uv]
package = false

[tool.uv.sources]
llm-sdk = { path = "llm_sdk", editable = true }

[tool.flake8]
exclude = [".venv", "__pycache__", ".mypy_cache", "llm_sdk", "moulinette"]

[tool.mypy]
exclude = ["llm_sdk/", "moulinette/"]

[[tool.mypy.overrides]]
module = ["llm_sdk", "llm_sdk.*"]
follow_imports = "skip"
